import keyMirror from 'keymirror'

export default keyMirror({
  ATTACHMENT_FAILED: null,
  ATTACHMENT_UPLOADED: null,
  ATTACHMENT_UPLOADING: null,

  CHANGELOG_FETCHED: null,
  CHANGELOG_FOLLOWED: null,
  CHANGELOG_SHOW_ALL: null,
  CHANGELOG_TIME_CHANGED: null,
  CHANGELOG_UNFOLLOWED: null,

  COMMENT_CREATING: null,
  COMMENT_DELETED: null,
  COMMENT_FORM_CHANGE: null,
  COMMENT_PUBLISHED: null,
  COMMENT_UPDATED: null,
  COMMENT_UPDATING: null,

  COMMENTS_FETCHED: null,
  COMMENTS_FETCHING: null,

  EMOJI_FETCHED: null,
  EMOJI_SELECTED: null,

  HIGHLIGHTS_FETCHED: null,
  HIGHLIGHT_IGNORED: null,
  HIGHLIGHT_USED: null,

  NOTIFICATIONS_FETCHED: null,
  NOTIFICATIONS_FETCHING: null,
  NOTIFICATIONS_READ: null,

  RESOURCE_FOUND: null,
  RESOURCE_NOT_FOUND: null,

  STORIES_FETCHED: null,
  STORIES_FETCHING: null,

  STORY_CREATING: null,
  STORY_FETCH: null,
  STORY_FETCHED: null,
  STORY_HEARTED: null,
  STORY_PUBLISHED: null,
  STORY_EDITING: null,
  STORY_UNHEARTED: null,
  STORY_UPDATED: null,

  STORY_FORM_CHANGE: null,
  STORY_FORM_CLEAR: null,

  USER_FETCHED: null,
  USER_SIGNIN: null,
  USER_SIGNOUT: null,
  USER_UPDATED: null,

  USER_PICKER_SET_HIGHLIGHT_INDEX: null,
  USER_PICKER_USERS_FETCHED: null
})
