import keyMirror from 'keymirror'

export default keyMirror({
  ADMIN_CHANGELOG_STATS_FETCHED: null,
  ADMIN_DATA_FETCHED: null,
  ADMIN_STORIES_FETCHED: null,
  ADMIN_USERS_DATA_FETCHED: null,

  ANALYTICS_CHANGELOG_CREATED: null,
  ANALYTICS_COMMENT_CREATED: null,
  ANALYTICS_ENGAGED: null,
  ANALYTICS_FOLLOWED: null,
  ANALYTICS_POST_CREATED: null,
  ANALYTICS_UPVOTE: null,
  ANALYTICS_USER_CREATED: null,

  API_ERROR: null,

  ATTACHMENT_FAILED: null,
  ATTACHMENT_SUCCEEDED: null,
  ATTACHMENT_UPLOADED: null,
  ATTACHMENT_UPLOADING: null,

  AVAILABLE_USERNAME_INPUT_VALIDATED: null,

  AUTHENTICATION_FORM_CHANGED: null,
  AUTHENTICATION_FORM_ERROR: null,
  AUTHENTICATION_FORM_ERROR_DISMISSED: null,
  AUTHENTICATION_FORM_FORM_CHANGED: null,
  AUTHENTICATION_FORM_HIDDEN: null,
  AUTHENTICATION_FORM_SHOWN: null,

  CHANGELOG_CHANGED: null,
  CHANGELOG_CREATE_FAILED: null,
  CHANGELOG_CREATING: null,
  CHANGELOG_CURRENT_CLEARED: null,
  CHANGELOG_DESTROYED: null,
  CHANGELOG_FETCHED: null,
  CHANGELOG_FOLLOWED: null,
  CHANGELOG_FORM_CHANGED: null,
  CHANGELOG_FORM_FOCUSED: null,
  CHANGELOG_MEMBERSHIPS_FETCHED: null,
  CHANGELOG_UNFOLLOWED: null,
  CHANGELOG_UPDATE_FAILED: null,
  CHANGELOG_UPDATED: null,
  CHANGELOG_UPDATING: null,

  CHANGELOGS_ALL_FETCHED: null,

  CHANGELOGS_MEMBERED_FETCHING: null,
  CHANGELOGS_MEMBERED_FETCHED: null,
  CHANGELOGS_MEMBERED_FETCH_FAILED: null,

  COMMENT_CREATING: null,
  COMMENT_DELETED: null,
  COMMENT_EDITING_TOGGLED: null,
  COMMENT_FORM_CHANGE: null,
  COMMENT_PUBLISHED: null,
  COMMENT_UPDATED: null,
  COMMENT_UPDATING: null,

  COMMENTS_FETCHED: null,
  COMMENTS_FETCHING: null,

  CONTRIBUTORS_RESET: null,
  CONTRIBUTORS_STRING_RECEIVED: null,
  CONTRIBUTORS_KEYDOWN: null,

  EMOJI_FETCHED: null,
  EMOJI_SELECTED: null,

  EMOJI_INPUT_BLURRED: null,
  EMOJI_INPUT_CLOSED: null,
  EMOJI_INPUT_FOCUSED: null,
  EMOJI_INPUT_OPENED: null,

  FEED_STORIES_FETCHED: null,

  FOLLOWINGS_FETCHING: null,
  FOLLOWINGS_FETCHED: null,
  FOLLOWINGS_FETCH_FAILED: null,

  FLAIRABLE_FLAIRING: null,
  FLAIRABLE_FLAIRED: null,
  FLAIRABLE_FLAIRING_FAILED: null,
  FLAIRABLE_UNFLAIRING: null,

  GIF_FORM_CHANGED: null,
  GIF_REACTION_FETCHED: null,

  GIFS_FETCHING: null,
  GIFS_FETCHED: null,
  GIFS_FETCHED_FROM_STORE: null,

  GITHUB_DRAFTS_LOADED: null,
  GITHUB_DRAFTS_LOADING: null,
  GITHUB_REPOS_FETCHED: null,
  GITHUB_REPOS_FETCHING: null,
  GITHUB_UNAUTHED_ERROR: null,

  GROUP_COLLAPSED: null,
  GROUP_DONE: null,
  GROUP_STORIES_FETCHED: null,

  HEARTABLE_HEARTING: null,
  HEARTABLE_HEARTED: null,
  HEARTABLE_HEARTING_FAILED: null,

  HEARTABLE_UNHEARTING: null,
  HEARTABLE_UNHEARTED: null,
  HEARTABLE_UNHEARTING_FAILED: null,

  HIGHLIGHTS_FETCHED: null,
  HIGHLIGHT_IGNORED: null,
  HIGHLIGHT_USED: null,

  IMPORT_FAILED: null,
  IMPORT_STARTED: null,
  IMPORT_STARTING: null,

  INVITATION_FETCHING: null,
  INVITATION_FETCHED: null,
  INVITATION_RESET: null,

  LOGIN_FORM_CHANGED: null,

  MEMBERSHIP_UPDATE_FAILED: null,
  MEMBERSHIP_UPDATED: null,
  MEMBERSHIP_UPDATING: null,
  MEMBERSHIP_DELETED: null,

  NEW_CHANGELOG_MEMBERSHIPS_FETCHED: null,

  NOTIFICATIONS_ACKD: null,
  NOTIFICATIONS_FETCHED: null,
  NOTIFICATIONS_FETCHING: null,
  NOTIFICATIONS_READ: null,

  PASSWORD_RESET_TOKEN_CONFIRMED: null,
  PASSWORD_RESET_TOKEN_FAILED: null,
  PASSWORD_RESET_TOKEN_REQUESTED: null,

  PENDING_MEMBERSHIP_UPDATED: null,

  PINNED_POSTS_FETCHED: null,
  PINNED_POSTS_FETCHING: null,

  PROFILE_CHANGELOGS_FETCHED: null,
  PROFILE_FETCHED: null,
  PROFILE_FETCHING: null,
  PROFILE_STORIES_FETCHED: null,
  PROFILE_UPDATE_FAILED: null,
  PROFILE_UPDATED: null,
  PROFILE_UPDATING: null,

  ROUTE_TRANSITIONED: null,
  RESOURCE_NOT_FOUND: null,

  SET_UPDATE_FAILED: null,
  SET_UPDATED: null,
  SET_UPDATING: null,

  SIGNIN_SCRIM_HIDDEN: null,
  SIGNIN_SCRIM_INITIALIZED: null,
  SIGNIN_SCRIM_SHOWN: null,

  SNACKBAR_ADD_TOAST: null,
  SNACKBAR_CLEAR: null,

  STORIES_FETCHED: null,
  STORIES_FETCHING: null,

  STORY_CREATING: null,
  STORY_DELETED: null,
  STORY_EDITING: null,
  STORY_FETCH: null,
  STORY_FETCHED: null,
  STORY_HEARTED: null,
  STORY_PUBLISHED: null,
  STORY_SUBSCRIBED: null,
  STORY_UNHEARTED: null,
  STORY_UNSUBSCRIBED: null,
  STORY_UPDATE_FAILED: null,
  STORY_UPDATED: null,
  STORY_UPDATING: null,

  STORY_FORM_CHANGE: null,
  STORY_FORM_CLEAR: null,

  STORY_PINNED: null,
  STORY_UNPINNED: null,

  TWEET_FAILED: null,

  TWEET_FORM_CHANGED: null,
  TWEET_FORM_DISMISSED: null,
  TWEET_FORM_ERROR_DISMISSED: null,
  TWEET_FORM_SUBMITTED: null,

  TWEET_SCRIM_HIDDEN: null,
  TWEET_SCRIM_SHOWN: null,

  TWITTER_ACCOUNT_UNLINKED: null,

  USER_SIGNIN: null,
  USER_SIGNOUT: null,
  USER_UPDATED: null,

  USER_PICKER_SET_HIGHLIGHT_INDEX: null,
  USER_PICKER_USER_SELECTED: null,
  USER_PICKER_USERS_CLEARED: null,
  USER_PICKER_USERS_FETCHED: null
})
