import keyMirror from 'keymirror'

export default keyMirror({
  ADMIN_DATA_FETCHED: null,
  ADMIN_STORIES_FETCHED: null,
  ADMIN_USERS_DATA_FETCHED: null,

  ANALYTICS_CHANGELOG_CREATED: null,
  ANALYTICS_COMMENT_CREATED: null,
  ANALYTICS_ENGAGED: null,
  ANALYTICS_FOLLOWED: null,
  ANALYTICS_POST_CREATED: null,
  ANALYTICS_UPVOTE: null,
  ANALYTICS_USER_CREATED: null,

  ATTACHMENT_FAILED: null,
  ATTACHMENT_UPLOADED: null,
  ATTACHMENT_UPLOADING: null,

  API_ERROR: null,

  CHANGELOG_CREATING: null,
  CHANGELOG_CREATE_FAILED: null,
  CHANGELOG_CURRENT_CLEARED: null,
  CHANGELOG_DESTROYED: null,
  CHANGELOG_FETCHED: null,
  CHANGELOG_FOLLOWED: null,
  CHANGELOG_MEMBERSHIPS_FETCHED: null,
  CHANGELOG_UNFOLLOWED: null,
  CHANGELOG_UPDATED: null,
  CHANGELOG_FORM_CHANGED: null,

  CHANGELOGS_ALL_FETCHED: null,

  COMMENT_CREATING: null,
  COMMENT_DELETED: null,
  COMMENT_EDITING_TOGGLED: null,
  COMMENT_FORM_CHANGE: null,
  COMMENT_PUBLISHED: null,
  COMMENT_UPDATED: null,
  COMMENT_UPDATING: null,

  COMMENTS_FETCHED: null,
  COMMENTS_FETCHING: null,

  CONTRIBUTORS_RESET: null,
  CONTRIBUTORS_STRING_RECEIVED: null,
  CONTRIBUTORS_KEYDOWN: null,

  EMOJI_FETCHED: null,
  EMOJI_SELECTED: null,

  FEED_STORIES_FETCHED: null,
  FOLLOWINGS_FETCHED: null,

  GIF_FORM_CHANGED: null,
  GIF_REACTION_FETCHED: null,

  GIFS_FETCHING: null,
  GIFS_FETCHED: null,
  GIFS_FETCHED_FROM_STORE: null,

  GROUP_COLLAPSED: null,
  GROUP_DONE: null,
  GROUP_STORIES_FETCHED: null,

  HIGHLIGHTS_FETCHED: null,
  HIGHLIGHT_IGNORED: null,
  HIGHLIGHT_USED: null,

  MEMBERSHIP_UPDATE_FAILED: null,
  MEMBERSHIP_UPDATED: null,
  MEMBERSHIP_UPDATING: null,

  NEW_CHANGELOG_MEMBERSHIPS_FETCHED: null,

  NOTIFICATIONS_ACKD: null,
  NOTIFICATIONS_FETCHED: null,
  NOTIFICATIONS_FETCHING: null,
  NOTIFICATIONS_READ: null,

  PENDING_MEMBERSHIP_UPDATED: null,

  PROFILE_CHANGELOGS_FETCHED: null,
  PROFILE_FETCHED: null,
  PROFILE_FETCHING: null,
  PROFILE_STORIES_FETCHED: null,
  PROFILE_UPDATE_FAILED: null,
  PROFILE_UPDATED: null,
  PROFILE_UPDATING: null,

  ROUTE_TRANSITIONED: null,
  RESOURCE_NOT_FOUND: null,

  SET_UPDATE_FAILED: null,
  SET_UPDATED: null,
  SET_UPDATING: null,

  STORIES_FETCHED: null,
  STORIES_FETCHING: null,

  STORY_CREATING: null,
  STORY_DELETED: null,
  STORY_FETCH: null,
  STORY_FETCHED: null,
  STORY_HEARTED: null,
  STORY_PUBLISHED: null,
  STORY_EDITING: null,
  STORY_SUBSCRIBED: null,
  STORY_UNHEARTED: null,
  STORY_UNSUBSCRIBED: null,
  STORY_UPDATED: null,

  STORY_FORM_CHANGE: null,
  STORY_FORM_CLEAR: null,

  USER_SIGNIN: null,
  USER_SIGNOUT: null,
  USER_UPDATED: null,

  USER_PICKER_SET_HIGHLIGHT_INDEX: null,
  USER_PICKER_USER_SELECTED: null,
  USER_PICKER_USERS_CLEARED: null,
  USER_PICKER_USERS_FETCHED: null
})
